name: Build all Platform

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-lin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install required libs
      run: |
        sudo apt-get update
        sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
    - name: Prepare
      run: |
        mkdir build-lin
    - name: CMake
      run: |
        cd build-lin
        pwd
        cmake ..
    - name: Build
      run: |
        cd build-lin
        pwd
        make -n
    - name: Upload plugin
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld-lin
        path: build-lin/lin_x64/
