name: Build all Platforms

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  #####################################
  # Linux with GCC
  build-lin:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install required libs
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libglu1-mesa-dev freeglut3-dev mesa-common-dev
    - name: Prepare
      run: |
        mkdir build-lin
    - name: CMake
      run: |
        cd build-lin
        pwd
        cmake -G Ninja ..
    - name: Build
      run: |
        cd build-lin
        pwd
        ninja
    - name: Upload plugin
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld
        path: build-lin/lin_*/
        if-no-files-found: error

  #####################################
  # MacOS with CMake/clang
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install required libs
      run: |
        brew install ninja
    - name: Prepare
      run: |
        mkdir build-mac
    - name: CMake
      run: |
        cd build-mac
        pwd
        cmake -G Ninja ..
    - name: Build
      run: |
        cd build-mac
        pwd
        ninja
    - name: Codesign and Notarization
      env: 
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
      if: env.MACOS_CERTIFICATE != null     # Only codesign if certificate defined
      run: |
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
        chmod a+x docker/sign-notarize
        ./docker/sign-notarize "build-mac/mac_x64/HelloWorld.xpl" "TwinFan.plugin.HelloWorld" certificate.p12 "${{ secrets.MACOS_CERT_PWD }}" "${{ secrets.NOTARIZATION_USERNAME }}" "${{ secrets.NOTARIZATION_PASSWORD }}"
    - name: Upload plugin
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld
        path: build-mac/mac_*/
        if-no-files-found: error

  #####################################
  # MacOS with XCode
  build-mac-xcode:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        xcodebuild -alltargets -quiet
    - name: Organise plugin for upload
      run: |
        mkdir build/mac_x64
        mv build/Release/HelloWorld.xpl build/mac_x64
    - name: Codesign executable
      env: 
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
        MACOS_CERT_PWD: ${{ secrets.MACOS_CERT_PWD }}
      if: env.MACOS_CERTIFICATE != null     # Only codesign if certificate defined
      run: |
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
        security create-keychain -p NotSoSecretAPwd build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p NotSoSecretAPwd build.keychain
        security import certificate.p12 -k build.keychain -P $MACOS_CERT_PWD -T /usr/bin/codesign
        security find-identity -v
        export MACOS_IDENTITY=`security find-identity -v | egrep -o '[0-9A-F]{40}'`
        echo $MACOS_IDENTITY
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k NotSoSecretAPwd build.keychain
        codesign --force -s $MACOS_IDENTITY build/mac_x64/HelloWorld.xpl -v
    - name: Upload plugin
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld
        path: build/mac_x*/
        if-no-files-found: error

  #####################################
  # Windows with MS Visual Studio
  build-win:
    if: ${{ false }}  # disable for now
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: CMD.EXE /C 'docker\build-win.cmd' "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" 'build'
    - name: Upload plugin
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld
        path: build/win_x*/
        if-no-files-found: error
