name: Build all Platform

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-lin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install required libs
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libglu1-mesa-dev freeglut3-dev mesa-common-dev
    - name: Prepare
      run: |
        mkdir build-lin
    - name: CMake
      run: |
        cd build-lin
        pwd
        cmake -G Ninja ..
    - name: Build
      run: |
        cd build-lin
        pwd
        ninja
    - name: Upload plugin
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld
        path: |
          build-lin/lin_x64/
        if-no-files-found: error

  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        xcodebuild -alltargets -quiet
    - name: Organise plugin for upload
      run: |
        mkdir build/mac_x64
        mv build/Release/HelloWorld.xpl build/mac_x64/
    - name: Upload plugin
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld
        path: |
          build/mac_x64/
        if-no-files-found: error
