name: Build all Platforms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:        # Can also be called manually for whatever reason

jobs:
  #####################################
  # Linux with GCC
  build-lin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2       # must checkout before we can use our own actions
    - uses: ./.github/actions/build-lin
      id: build
      with:
        pluginName: HelloWorld
    - uses: ./.github/actions/upload-plugin
      with:
        pluginName: HelloWorld
        archFolder: lin_x64
        xplFileName: "${{ steps.build.outputs.xpl-file-name }}"

  #####################################
  # MacOS with CMake/clang and sign/notarize in self-written script
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build-mac
      id: build
      with:
        pluginName: HelloWorld
    - name: Codesign and Notarization
      env: 
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
      if: ${{ false }}   # sign/notarize disabled
#      if: env.MACOS_CERTIFICATE != null     # Only codesign if certificate defined
      run: |
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
        chmod a+x docker/sign-notarize
        ./docker/sign-notarize "build-mac/mac_x64/HelloWorld.xpl" "TwinFan.plugin.HelloWorld" certificate.p12 "${{ secrets.MACOS_CERT_PWD }}" "${{ secrets.NOTARIZATION_USERNAME }}" "${{ secrets.NOTARIZATION_PASSWORD }}"
    - uses: ./.github/actions/upload-plugin
      with:
        pluginName: HelloWorld
        archFolder: mac_x64
        xplFileName: "${{ steps.build.outputs.xpl-file-name }}"

  #####################################
  # Windows with MS Visual Studio
  build-win:
    runs-on: windows-2022
    if: ${{ false }}  # disable for now
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: CMD.EXE /C 'docker\build-win.cmd' "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" 'build'
    - name: Upload plugin
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld
        path: build/win_x*/
        if-no-files-found: error
